Part1
0bi0n3/PFMCPP_Project6 pull request #1
Opened 2023-06-05 15:57 UTC by 0bi0n3

Attempted steps 1-12, encountered some errors when compiling but attempted fixes prior to sending to review. Code compiles, I am unsure if results are correct.

2023-06-06 00:56 UTC, matkatmusic requested changes

2023-06-06 00:56 UTC, matkatmusic commented on main.cpp
> +        if( a->a > b->a ) return b;
The member variable was called `value`.  You did not need to rename it
- [x] revise

2023-06-06 00:56 UTC, matkatmusic commented on main.cpp
> +        std::cout << "U's var1 updated value: " << this->var1 << std::endl;
What do we always do before using a pointer?
- [x] revise

2023-06-06 00:56 UTC, matkatmusic commented on main.cpp
> +        std::cout << "U's var1 updated value: " << that->var1 << std::endl;
What do we always do before using a pointer?
- [x] revise

2023-06-06 10:39 UTC, 0bi0n3 commented on main.cpp
> +        if( a->a > b->a ) return b;
I think I see it!
I didn't need to match the a & b variables, these are already provided in the `T* compare(T* a, T* b)` function.

Whereas the constructor in `T(float v, const char* str) : value(v), name(str) {}` hints at the variable name with `v`?

Please let me know if I have misunderstood that.

2023-06-06 10:40 UTC, 0bi0n3 commented on main.cpp
> +        std::cout << "U's var1 updated value: " << this->var1 << std::endl;
Check for `nullptr`!

Fixed this with an `if` conditional.

2023-06-06 10:41 UTC, 0bi0n3 commented on main.cpp
> +        std::cout << "U's var1 updated value: " << that->var1 << std::endl;
Check for `nullptr`!

Fixed this with two `if` conditionals for both pointers.

2023-06-07 17:15 UTC, matkatmusic approved these changes

2023-06-07 17:15 UTC, merged